//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESTDataBaseTool {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("201.20.7.33")]
        public string HostOrigem {
            get {
                return ((string)(this["HostOrigem"]));
            }
            set {
                this["HostOrigem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("201.20.7.33")]
        public string HostDestino {
            get {
                return ((string)(this["HostDestino"]));
            }
            set {
                this["HostDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("postgres")]
        public string UsuarioOrigem {
            get {
                return ((string)(this["UsuarioOrigem"]));
            }
            set {
                this["UsuarioOrigem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("postgres")]
        public string UsuarioDestino {
            get {
                return ((string)(this["UsuarioDestino"]));
            }
            set {
                this["UsuarioDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TjYz3m")]
        public string SenhaOrigem {
            get {
                return ((string)(this["SenhaOrigem"]));
            }
            set {
                this["SenhaOrigem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TjYz3m")]
        public string SenhaDestino {
            get {
                return ((string)(this["SenhaDestino"]));
            }
            set {
                this["SenhaDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5890")]
        public string PortaOrigem {
            get {
                return ((string)(this["PortaOrigem"]));
            }
            set {
                this["PortaOrigem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5890")]
        public string PortaDestino {
            get {
                return ((string)(this["PortaDestino"]));
            }
            set {
                this["PortaDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DES_NESTRIS")]
        public string DBOrigem {
            get {
                return ((string)(this["DBOrigem"]));
            }
            set {
                this["DBOrigem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SBX_NESTRIS")]
        public string DBDestino {
            get {
                return ((string)(this["DBDestino"]));
            }
            set {
                this["DBDestino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\NEST\\BKP\\DataBase\\Scripts\\")]
        public string Diretorio {
            get {
                return ((string)(this["Diretorio"]));
            }
            set {
                this["Diretorio"] = value;
            }
        }
    }
}
